from datetime import datetime
birthday = datetime(1998, 2, 14)
print(birthday.strftime("%Y-%m-%d"))
print(birthday.strftime("%y.%m.%d"))
print(birthday.strftime("%y#%m#%d"))
print(birthday.strftime("%y/%m/%d"))
print(birthday.strftime("%y,%m,%d"))
print(birthday.strftime("%y*%m*%d"))
print(birthday.strftime("%y!%m!%d"))
print(birthday.strftime("%y^%m^%d"))
print(birthday.strftime("%m@%y@%y"))
print(birthday.strftime("%m=%d=%Y"))
print(birthday.year, birthday.month, birthday.day)
print("----------------------------")
print(birthday.strftime("%Y-%m-%d"))
print(birthday.strftime("%Y,%B,%d"))
print(birthday.strftime("%Y-%b-%d"))
print(birthday.strftime("%Y-%m-%d"))